[features]
seeds = false
skip-lint = false
[programs.devnet]
encrypted = "HWkxWXKvvrUi8EoS6xZ391ncPSr9dFNTw275HpGJ8Rwy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/lousydropout/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
