[features]
seeds = false
skip-lint = false
[programs.devnet]
encrypted = "EH315jfjYJjcom6QdQQXz2EViVQrKJ9numcPXP2RRfeZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/lousydropout/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
